cmssw_compile:
  tags:
    - cvmfs
  variables:
    CMS_PATH: /cvmfs/cms.cern.ch
    CMSSW_RELEASE: CMSSW_11_0_3
  script:
    - shopt -s expand_aliases
    - set +u && source ${CMS_PATH}/cmsset_default.sh; set -u
    - cmsrel ${CMSSW_RELEASE}
    - cd ${CMSSW_RELEASE}/src
    - cmsenv
    - mkdir -p ISpy/Services
    - mv ${CI_PROJECT_DIR}/src ${CMSSW_BASE}/src/ISpy/Services/
    - mv ${CI_PROJECT_DIR}/interface ${CMSSW_BASE}/src/ISpy/Services/
    - mv ${CI_PROJECT_DIR}/test ${CMSSW_BASE}/src/ISpy/Services/
    - mv ${CI_PROJECT_DIR}/BuildFile.xml ${CMSSW_BASE}/src/ISpy/Services/
    - scram b

